- playground/index.html
- playground/playground.js
As per a [recent discussion](https://lists.w3.org/Archives/Public/public-linked-json/2015Jan/0030.html) on the mailing list (cc @msporny), this adds (anonymous) gist (de)serialization to the playground.
Here is an example URL for loading a gist:
http://bollwyvl.github.io/json-ld.org/playground/#/gist/12397f939500d17a1a9f
With the supporting gist:
https://gist.github.com/anonymous/12397f939500d17a1a9f
This is really more of a starting point than anything else.
- There is a bit of a mismatch between what is shown vs what is stored: the name, which is just a good idea for the gist, doesn't have anyplace to live.
- At present, there is no way to create a gist as a particular user, which would be nice... last I checked that required a minimal oauth backend to do properly.
- On the list, …
> adding basic gist integration

- playground/index.html
- playground/playground-examples.js
- playground/playground.js
Adds an initial Activity Streams 2.0 example along with a redirection for the 
development context document.
> Add Initial Activity Streams 2.0 Example

- playground/playground-examples.js
Update example to point to the dev location for the context to avoid the warning. This ought to be temporary
> Update example to point to dev context

- index.html
The markup was using the `container` and `row` class on the same element. This patch moves the `row` class to the child `<div>` and moves the `offset` and `span` classes to the `<p>`.
> Center align "Playground" section on homepage

- spec/latest/json-ld-framing/index.html
so, a frame is like a template of what you want the final json-ld to look like?  Been banging my head on this spec with no luck.
do you happen to know if https://github.com/digitalbazaar/pyld and https://github.com/digitalbazaar/jsonld.js implement the same version of frames?
> fix some broken links in framing spec

- schemas/jsonld-schema.json
Hi, I believe I found two small issues on the jsonld-schema.
A hidden U+FEFF char on the begining of the file was breaking some parsers, for example in ruby: 
```
content  = File.read('./schemas/jsonld-schema.json')
JSON.parse content  # raise an Error
```
The schema definition seems to have a validation mistake. I.e, almost any invalid json-ld would pass.
This happens because we are using a `anyOf` clause on the definitions, so if we provide an invalid `@context`, the validator will check for the next and one of them almost always pass. This way the json would be invalid only if context, common and graph are invalid at the same time. 
To fix, we just have to change to a `allOf` clause, i.e, each of the defintions must be valid at the same time.
To ilustrate this issue, I'm providing a …
> Fix json-schema validation

- spec/latest/json-ld-api/index.html
- spec/latest/json-ld-framing/index.html
- test-suite/tests/frame-0046-frame.jsonld
- test-suite/tests/frame-0046-in.jsonld
- test-suite/tests/frame-0046-out.jsonld
- test-suite/tests/frame-0047-frame.jsonld
- test-suite/tests/frame-0047-in.jsonld
- test-suite/tests/frame-0047-out.jsonld
- test-suite/tests/frame-0048-frame.jsonld
- test-suite/tests/frame-0048-in.jsonld
- test-suite/tests/frame-0048-out.jsonld
- test-suite/tests/frame-0049-frame.jsonld
- test-suite/tests/frame-0049-in.jsonld
- test-suite/tests/frame-0049-out.jsonld
- test-suite/tests/frame-0050-frame.jsonld
- test-suite/tests/frame-0050-in.jsonld
- test-suite/tests/frame-0050-out.jsonld
- test-suite/tests/frame-manifest.jsonld
This PR closes #118, adding support for named graphs when framing, and allows framing to use either the merged graph or the default graph. It also adds an algorithm for creating the merged node set.
> Issue 118 graph framing

- playground/index.html
- playground/jsonld-signatures.js
- playground/playground.css
- playground/playground.js
We have signature validation with bitcoin keys [working and live on a demo server](http://thawing-inlet-70039.herokuapp.com/playground/).  
**We should wait for the following to be merged before merging this PR:**
Once https://web-payments.org/contexts/security-v1.jsonld contains EcdsaKoblitzSignature2016 we can: 
Nice to have but probably not critical:
https://github.com/web-payments/web-payments.org/issues/41
cc @ChristopherA @msporny
> Add JSON-LD verification via BTC public key

- playground/index.html
Fixes the Mixed Content mess...for real.
I have this in place on the [LevelGraph Playground](http://wileylabs.github.io/levelgraph-playground) and it works.
Cheers!
🎩
> Add CSP: upgrade-insecure-requests

- spec/latest/json-ld/index.html
> Add text clarifying what an "unconnected node" is.

- spec/latest/json-ld-api/index.html
- test-suite/tests/expand-l001-in.jsonld
- test-suite/tests/expand-l001-out.jsonld
- test-suite/tests/expand-manifest.jsonld
which is allowed in the syntax. Such values are ignored.
Fixes #375.
> In expansion, allow a language map to have a `null` value

- spec/latest/json-ld/index.html
Fixes the description of how type maps work in the syntax document, as reported by @jefferys.
> Fix text describing a type map

- spec/latest/json-ld-api/index.html
- spec/latest/json-ld/index.html
- test-suite/tests/compact-manifest.jsonld
- test-suite/tests/compact-s001-context.jsonld
- test-suite/tests/compact-s001-in.jsonld
- test-suite/tests/compact-s001-out.jsonld
- test-suite/tests/compact-s002-context.jsonld
- test-suite/tests/compact-s002-in.jsonld
- test-suite/tests/compact-s002-out.jsonld
- test-suite/tests/error-manifest.jsonld
- test-suite/tests/error-s001-in.jsonld
- test-suite/tests/error-s002-in.jsonld
Add grammar and algorithm changes to allow `@container` to be an array including `@set` along with another container type.
Fixes #269. Fixes #407.
> @container as array including @set.

- test-suite/tests/compact-0074-context.jsonld
- test-suite/tests/compact-0074-in.jsonld
- test-suite/tests/compact-0074-out.jsonld
- test-suite/tests/compact-manifest.jsonld
I add these tests because probably there is a bug in jsonld.js implementation which prevents compacting fields mapped as container list with type of id.
Not working example on JsonLD playground: [link](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%7B%22name%22%3A%7B%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40list%22%2C%22%40id%22%3A%22https%3A%2F%2Fschema.org%2Fname%22%7D%7D%2C%22name%22%3A%5B%5D%7D&context=%7B%22%40context%22%3A%7B%22name%22%3A%7B%22%40type%22%3A%22%40id%22%2C%22%40container%22%3A%22%40list%22%2C%22%40id%22%3A%22https%3A%2F%2Fschema.org%2Fname%22%7D%7D%7D)
Working example on Markus Lanthaler JsonLD playground: [link](http://www.markus-lanthaler.com/jsonld/playground/?json-ld=%7B%0A%20%20%22%40context%22%3A%20%7B%0A%20%2 …
> Add test for compact property with @type as @id and @container as @list

- test-suite/context.jsonld
- test-suite/manifest.jsonld
- test-suite/tests/compact-0038a-out.jsonld
- test-suite/tests/compact-manifest.jsonld
- test-suite/tests/error-manifest.jsonld
- test-suite/tests/expand-manifest.jsonld
- test-suite/tests/flatten-manifest.jsonld
- test-suite/tests/frame-manifest.jsonld
- test-suite/tests/fromRdf-manifest.jsonld
- test-suite/tests/remote-doc-manifest.jsonld
- test-suite/tests/toRdf-manifest.jsonld
- test-suite/vocab.html
- test-suite/vocab.jsonld
- test-suite/vocab.ttl
Update test vocabulary location to be https. Add `specVersion`.
Fixes #489.
> Mark 1.1 tests with "specVersion": "1.1", which is independent of "processingMode".

- spec/latest/json-ld-framing/index.html
This removes support for `@link`, which could be re-introduced sometime later, perhaps in a different document. This feature never had tests due to the inherent problems with not being able to serialize such a linked document.
Upon closing, issues #140 and #531 will remain open, but be removed from the 1.1 milestone.
For issue #140 and obviates issue #531.
> Remove object linking in the framing document

- spec/latest/json-ld-api/index.html
- test-suite/tests/expand-0088-in.jsonld
- test-suite/tests/expand-0088-out.jsonld
- test-suite/tests/expand-manifest.jsonld
> Don't expand non-string native values to node objects.

- spec/latest/json-ld-api/index.html
- spec/latest/json-ld-framing/index.html
when framing.
Fix frame matching algorithm to not match a node if frame has a non-empty `@id`, which is not an empty dictionary.
Fixes #532.
> Fix expansion algorithm to not reject a node containing only `@id`

- LICENSE.md
[W3C Software and Document License](h…ttps://www.w3.org/Consortium/Legal/copyright-software).
Fixes #560.
> Update main site license to use W3C Software and Document License.

- playground/playground.js
Attempts to fix #523.
Live version at: https://peaceful-inlet-31266.herokuapp.com/playground/
Sample testnet keypair for your testing pleasure:
`cPXLG42L3AyiKukbNdzYecS3JVC71gRhbcZEKUWNYtUXWZDnCpkQ`
`myGEzNpxqbVkyDewZuCzEmnse8jExiH2gQ`
@ChristopherA is this what you had in mind?
> public key in hex

- playground/playground.js
That was added before AS2 had a real home for its context.  It has one
now, so this is unnecessary.
> Remove ActivityStreams context from contextMap.

- spec/latest/common/terms.html
- spec/latest/json-ld-api/index.html
- spec/latest/json-ld/index.html
to clarify that it describes only IRIs relative to the document base, not the **vocabulary mapping**.
Add additional explanatory text on relative IRIs to distinguish them from properties, values of `@type`, or values of properties defined to be vocabulary relative.
Fixes #488.
> Update relative IRI definition

- spec/latest/json-ld-api/index.html
and all uses where _document relative_ is false, which is the default value.
Fixes #562.
> Remove an errant _document relative_ flag to compact IRI

- spec/latest/json-ld-framing/index.html
This also relates to #486.
As the Framing document is expected to continue for the long term, this PR makes editors and authors consistent with the API document (other than moving @msporny up in the order of authorship contributions).
> Update editors/authors for framing to be consistent with API document.

- spec/latest/json-ld-api/index.html
- test-suite/tests/compact-c011-context.jsonld
- test-suite/tests/compact-c011-in.jsonld
- test-suite/tests/compact-c011-out.jsonld
- test-suite/tests/compact-manifest.jsonld
Look at term contexts from `@type` before starting to compact object members. Adds test.
Fixes #546.
> Fix compaction on scoped contexts based on @type

- test-suite/tests/frame-manifest.jsonld
I assume this was the one to remove.  But maybe the prune flag isn't needed.
> Remove duplicate option property.

- spec/latest/json-ld-api/index.html
- test-suite/tests/compact-0080-out.jsonld
- test-suite/tests/compact-0083-out.jsonld
- test-suite/tests/frame-0047-out.jsonld
- test-suite/tests/frame-0048-out.jsonld
- test-suite/tests/frame-0049-out.jsonld
- test-suite/tests/frame-0050-out.jsonld
- test-suite/tests/frame-p049-out.jsonld
don't force value into an array.
> When compacting `@graph`, where a container type can't be used

- spec/latest/json-ld/index.html
> Clarify that term definitions can replace previous scoped contexts.

- test-suite/tests/compact-0091-in.jsonld
- test-suite/tests/compact-0092-context.jsonld
- test-suite/tests/compact-0092-in.jsonld
- test-suite/tests/compact-0092-out.jsonld
- test-suite/tests/compact-0093-context.jsonld
- test-suite/tests/compact-0093-in.jsonld
- test-suite/tests/compact-0093-out.jsonld
- test-suite/tests/compact-manifest.jsonld
Compact tests changes:
- Copy 0090 to 0091 and use compactArrays=false.
- Move 0091 to 0092.
- Copy 0091 to 0093 and use compactArrays=false.
This is related to a jsonld.js and pyld fix that was flattening single items in an array without checking compactArrays flag.  Please verify the output.
> Add `@graph` compactArrays tests.

- spec/latest/json-ld/index.html
A set object has `@set`, not `@list` as a component.
Fixes #615.
> Fix set object description

- spec/latest/json-ld-api/index.html
Add text to end of compaction algorithm for case when result is an empty array.
Fixes #608.
cc/@cwebber
>  Add text to end of compaction algorithm for empty array

- spec/latest/json-ld-api/index.html
- spec/latest/json-ld/index.html
- test-suite/tests/compact-c012-context.jsonld
- test-suite/tests/compact-c012-in.jsonld
- test-suite/tests/compact-c012-out.jsonld
- test-suite/tests/compact-manifest.jsonld
- test-suite/tests/expand-c011-in.jsonld
- test-suite/tests/expand-c011-out.jsonld
- test-suite/tests/expand-manifest.jsonld
lexicographicall…y by their compacted value. When compacting, first turn types into their compacted form, and then process by lexicographical ordering. When expanding, simply order the existing values.
Fixes #616
> Describe that scoped contexts on `@type` are ordered

- spec/latest/json-ld-api/index.html
Add missing text to compaction algorithm when a list object is set as the value of a term where the container does not have `@list`.
Fixes #607.
> Add missing text to compaction algorithm

- spec/latest/json-ld-api/index.html
- spec/latest/json-ld/index.html
this affects only the term selection algorithm in _IRI Compaction_.
Fixes #571.
> Limit the use of `@none` in language and index maps to 1.1 only

- spec/latest/json-ld-framing/index.html
- test-suite/tests/frame-manifest.jsonld
and make it dependent on **processing mode**.
Fixes #627.
> Remove the `pruneBlankNodeIdentifiers` option for framing

- spec/latest/common/terms.html
- spec/latest/json-ld-api/index.html
- spec/latest/json-ld-framing/index.html
- spec/latest/json-ld/index.html
rather than it's expanded IRI, to find a scoped context.
Fixes #521.
> Clarify that scoped contexts on `@type` use the term used

- spec/latest/json-ld/index.html
to be consistent with API processing.
Fixes #636.
> Add text to the grammar to restrict the content model of `@reverse`

- spec/latest/json-ld-api/index.html
- spec/latest/json-ld-framing/index.html
- test-suite/tests/frame-manifest.jsonld
- test-suite/tests/frame-p050-frame.jsonld
- test-suite/tests/frame-p050-in.jsonld
- test-suite/tests/frame-p050-out.jsonld
* Add statement to Conformance sections of API and Framing that algorithm steps describing operations on keywords also apply to aliases of those keywords to make it clear.
* Add example using alias of `@id`.
Fixes #611.
> Clarify BNode pruning with keyword aliases

- spec/latest/json-ld-api/index.html
> Require that a remote context only be dereferenced once.

- spec/latest/json-ld-api/index.html
- spec/latest/json-ld/index.html
- test-suite/tests/compact-manifest.jsonld
- test-suite/tests/compact-p001-out.jsonld
- test-suite/tests/expand-manifest.jsonld
- test-suite/tests/expand-p001-in.jsonld
- test-suite/tests/expand-p001-out.jsonld
- test-suite/tests/expand-p002-in.jsonld
- test-suite/tests/expand-p002-out.jsonld
- test-suite/tests/expand-p003-in.jsonld
- test-suite/tests/expand-p003-out.jsonld
- test-suite/tests/expand-p004-in.jsonld
- test-suite/tests/expand-p004-out.jsonld
it only conflicts… if `processingMode` is set to something else in the API. Also changes term selection for compact IRIs in 1.0 mode as a necessary byproduct of this approach.
Fixes #581
> Relax to allow `@version` to be set in any context

- test-suite/tests/frame-g010-frame.jsonld
- test-suite/tests/frame-g010-in.jsonld
- test-suite/tests/frame-g010-out.jsonld
- test-suite/tests/frame-manifest.jsonld
This follows on from a bug and fix i filed on [pyld](https://github.com/digitalbazaar/pyld): [issue 81](https://github.com/digitalbazaar/pyld/pull/81). At @davidlehn 's request i am submitting the test so that future implementations don't make the same mistake. 
As far as i can tell there aren't any tests that deal with multiple named graphs yet, so i hope this is useful. Please note that none of the following implementations currently comply with what i think should be the results:
* [Stable JSON-LD playground](https://json-ld.org/playground/#startTab=tab-framed&copyContext=true&json-ld=%7B%22%40context%22%3A%7B%22%40vocab%22%3A%22http%3A%2F%2Fexample.com%2F%22%2C%22loves%22%3A%7B%22%40type%22%3A%22%40id%22%7D%2C%22unionOf%22%3A%7B%22%40type%22%3A%22%40id%22%2C%22%40id%22%3A%22owl%3Aunion …
> New test: frame-g010: Multiple named graphs

- contexts/person
- contexts/person.jsonld
this makes it consistent with example usage.
> Update term for "born" and "died" to be xsd:date not xsd:dateTime

- index.html
This adds https://github.com/rubensworks/jsonld-streaming-parser.js to the list of JS implementations.
> Add jsonld-streaming-parser.js to list of implementations

- index.html
This PR adds [jsonld-streaming-serializer.js](https://github.com/rubensworks/jsonld-streaming-serializer.js) to the list of JavaScript implementations.
> Add jsonld-streaming-serializer.js to list of implementations

- index.html
Signed-off-by: Tomislav Markovski <tmarkovski@gmail.com>
dotNetRDF supports JSON-LD 1.0 and the team is working on adding 1.1 support.
> Add dotNetRDF to available c# libraries

- spec/latest/json-ld-api-best-practices/index.html
Add "annoying warning" to redirect readers to the WG version of the best-practices document.
Searching for "JSON-LD Best Practices" still favors the old CG version of the document.
> Add "Specification Moved" warning to the old best practices document.

- schemas/jsonld-schema.json
The JSON-Schema should have an official URI in `$id` for referencing.
> Add JSON Schema URI in $id

- spec/latest/.htaccess
RDF Dataset Normalization (`json-ld/normalization`) was renamed to RDF Dataset Canonicalization (`json-ld/rdf-dataset-canonicalization`): https://github.com/json-ld/rdf-dataset-canonicalization/commit/0522d97b3d60af85f270e78be7166cece4959091, https://github.com/json-ld/rdf-dataset-canonicalization/pull/20.
The redirect at `/spec/latest/rdf-dataset-normalization/` currently points to the old URL which is a broken link now. This PR
adds a new redirect at `/spec/latest/rdf-dataset-canonicalization/` to reflect the document's new name and repo id, and updates the existing route `/spec/latest/rdf-dataset-normalization/`, to redirect to this new route. This is intended to fix the broken link, following the pattern of how `rdf-graph-normalization` redirects to `rdf-dataset-normalization`.
> Update link to RDF Dataset Canonicalization

- playground/dev/index.html
- playground/index.html
- playground/playground.js
- Updates jsonld.js to 8.0.0.
- Add safe mode option UI.
- Show error details if available.  Hopefully this doesn't have degenerate cases involving huge errors or recursive serialization.  A built project would use other libraries to avoid that but this is difficult for now.
- Disables signature tabs since old jsonld-signatures no longer works with newer jsonld.js.  Bundled code and default suites are not distributed.  Need to move this to a build process if that functionality is to be kept.
> Update jsonld js and add safe mode support.

- spec/latest/.htaccess
This will forward (301) requests for the latest versions of specs to their /TR locations. Note that the site menu drop-downs already do this, as well as forward the latest drafts to w3c.github.io/...
I didn't actually remove the latest versions of the specs from the repo, but they shouldn't be accessible via HTTP. Neither did I attempt to add any robots.txt to keep them from being indexed.
> Add back forwarding rules for latest specs to /TR.

- index.html
- spec/latest/json-ld-api-best-practices/index.html
- spec/latest/json-ld-connect/index.html
- spec/latest/json-ld-rdf/index.html
GitHub should be stylized with a capital "H".
Generated the PR by executed `find . -type f -exec sed -i '' "s/Github/GitHub/g" {} +` from the project root.
> Rename 'Github' to 'GitHub'

- playground/1.0/playground.js
- playground/playground.js
Convert both "http://schema.org/" and "http://schema.org" to "https://schema.org/".
This covers up lower level issues, but will help address a common use case.
Closes: https://github.com/json-ld/json-ld.org/issues/798
> Fix "http://schema.org" processing.

- playground/index.html
The CHAPI Playground has moved to be the Verifiable Credentials Playground at https://vcplayground.org/
> Change CHAPI Playground links.

- playground/playground.js
- Log error as object property so details can be inspected.
- Add UI note to check console.
- This is a basic update to improve error logging.  The current code is logging the processing error, but at least in the case of recent Chromium, the direct Error logging seems to hide added properties such as `details` used here. This low effort fix at least allows users to dig into internal jsonld.js errors.  Future work includes better custom error handling for common issue reporting in the UI directly.
> Improve logging of processing errors.

- index.html
Hi,
please add ld-cli on the list, I've just noticed there is a new section `Command Line`. 
Thank you
> Add ld-cli native executable for Ubuntu,MacOS, and Win

- .eleventy.js
- _includes/implementation-item.liquid
- index.html
- index.yaml
- package.json
- **Add YAML as a data type in 11ty.**
- **Move implementation info to data.**
> Data driven implementations list.
