- playground/playground.js
> fixing copy-pasta mistake

- playground/playground-examples.js
Use the official context document location and use Create instead of Post
> update activity streams example

- learn.html
:pencil2: :notebook:  :computer: :coffee:
> Add Meaningful Data APIs post

- playground/playground.js
This PR fixes an issue introduced in #432.
> Algorithm fix for #432

- spec/latest/common/terms.html
- spec/latest/json-ld-api/index.html
- spec/latest/json-ld-framing/index.html
- spec/latest/json-ld/index.html
Updates WebIDL, Promises and ECMASCRIPT. Uses new `data-cite` attribute, and adds a WebIDL index.
> Respec updates

- spec/latest/common/terms.html
- spec/latest/json-ld-api/index.html
- spec/latest/json-ld-framing/index.html
- spec/latest/json-ld/index.html
Update internal externalDFN references to be dfn with data-cite. Fix framing respec errors.
> Use data-cite in definitions that are reflections of external definitions

- CONTRIBUTING.md
- LICENSE.md
Based off of comments in #417.
> Add License and Contributing files

- playground/index.html
- playground/jsonld-vis.css
- playground/jsonld-vis.js
- playground/playground.js
Uses https://github.com/scienceai/jsonld-vis (Apache License 2.0)
...which uses https://github.com/d3/d3 (BSD-3)
...and https://github.com/Caged/d3-tip (MIT)
Fixes #383 
❤️
🎩
> Add Visualized tab to playground

- spec/latest/json-ld/index.html
> Update RDFa example to use RDFa 1.1 Lite.

- playground/playground.js
This seems to be the minimum change to fix #513.
> fix remote doc load bug

- test-suite/tests/compact-0075-context.jsonld
- test-suite/tests/compact-0075-in.jsonld
- test-suite/tests/compact-0075-out.jsonld
- test-suite/tests/compact-0076-context.jsonld
- test-suite/tests/compact-0076-in.jsonld
- test-suite/tests/compact-0076-out.jsonld
- test-suite/tests/compact-manifest.jsonld
- test-suite/tests/flatten-0047-in.jsonld
- test-suite/tests/flatten-0047-out.jsonld
- test-suite/tests/flatten-manifest.jsonld
> Add tests based on those found to have been problematic in pyld.

- spec/latest/json-ld/index.html
> Clarify that multiple property values may be of different types

- spec/latest/json-ld-framing/index.html
- spec/latest/json-ld/index.html
@elf-pavlik see if this change satisfies your needs.
> Issue 555 improve embedding examples

- test-suite/tests/expand-0088-in.jsonld
- test-suite/tests/expand-0088-out.jsonld
For completness, test the default along with other methods.
> Add default coercion test.

- test-suite/tests/expand-0089-in.jsonld
- test-suite/tests/expand-0089-out.jsonld
- test-suite/tests/expand-0090-in.jsonld
- test-suite/tests/expand-0090-out.jsonld
- test-suite/tests/expand-0091-in.jsonld
- test-suite/tests/expand-0091-out.jsonld
- test-suite/tests/expand-manifest.jsonld
Related to:
https://github.com/json-ld/json-ld.org/issues/535
> Add empty and relative @base tests.

- test-suite/tests/error-manifest.jsonld
- test-suite/tests/error-p010-context.jsonld
- test-suite/tests/error-p010-in.jsonld
- test-suite/tests/error-p011-context.jsonld
- test-suite/tests/error-p011-in.jsonld
- test-suite/tests/error-p012-context.jsonld
- test-suite/tests/error-p012-in.jsonld
- test-suite/tests/error-p013-context.jsonld
- test-suite/tests/error-p013-in.jsonld
- test-suite/tests/error-p014-context.jsonld
- test-suite/tests/error-p014-in.jsonld
- test-suite/tests/error-p015-context.jsonld
- test-suite/tests/error-p015-in.jsonld
For invalid term definition keys and container values.
> Add 1.0 processingMode checks

- test-suite/tests/fromRdf-0023-in.nq
- test-suite/tests/fromRdf-0023-out.jsonld
- test-suite/tests/fromRdf-manifest.jsonld
See https://github.com/digitalbazaar/jsonld.js/issues/205.
> Test fromRDF with nil subject.

- spec/latest/json-ld-api/index.html
> Add punctuation to IRI compaction algorithm step.

- spec/latest/json-ld-api/index.html
- spec/latest/json-ld-framing/index.html
... based on the presence of the `framing` option. This allows the flag to be turned off when encountering `@default`.
> Update the Expansion Algorithm to use an explicit _frame expansion_ flag

- test-suite/tests/compact-0090-context.jsonld
- test-suite/tests/compact-0090-in.jsonld
- test-suite/tests/compact-0090-out.jsonld
- test-suite/tests/compact-0091-context.jsonld
- test-suite/tests/compact-0091-in.jsonld
- test-suite/tests/compact-0091-out.jsonld
- test-suite/tests/compact-manifest.jsonld
These test compact, though the fix to make these pass requires updates to some framing tests.
> Add tests for 1.1 graph array behavior.

- spec/latest/json-ld-api/index.html
- spec/latest/json-ld-framing/index.html
as ReSpec will shortly… provide a UI for highlighting variables in an algorithm.
Change CSS for algorithm to set it on the section or other containing element and not repeat on each ol, which aids in finding all variables in an algorithm.
Fix up some use of term references which should be variables.
> Use var instead of em for algorithm variables

- spec/latest/json-ld/index.html
- test-suite/tests/compact-0091-context.jsonld
- test-suite/tests/compact-0091-in.jsonld
- test-suite/tests/compact-0091-out.jsonld
- test-suite/tests/compact-manifest.jsonld
- test-suite/tests/compact-p008-context.jsonld
- test-suite/tests/compact-p008-in.jsonld
- test-suite/tests/compact-p008-out.jsonld
> Add @prefix: true example add @prefix: false test

- spec/latest/json-ld-api/index.html
> Add Term Selection algorithm examples.

- index.html
This probably needs more improvement, but my hopes is that we can get some sign posts added to encourage json-ld.org visitors to join the Working Group activities.
Happy to field feedback!
🎩
> Promote the Working Group

- index.html
Tweaked some URLs of past implementations, found some new ones, and added some RDFa because I'm geeky that way. 🤓 
Cheers!
🎩
> Implementations updates

- spec/latest/json-ld-api/index.html
- spec/latest/json-ld-framing/index.html
- spec/latest/json-ld/index.html
Based on warnings shown by PR preview.
> Add unavoidable warnings directing people to the current WG drafts.

- playground/playground-examples.js
- spec/latest/json-ld/index.html
which is often confused with dcelements.
> Favor "dcterms" over simply "dc"

- index.html
Hopefully helps promote the library progresses made, and encourages "winning the badge" for 1.1 implementation. 😀
> Developer section updates

- images/index.html
- index.html
- learn.html
- playground/1.0/index.html
- playground/dev/index.html
- playground/index.html
- primer/index.php
- requirements/index.php
- spec/index.php
- test-suite/index.html
- test-suite/vocab.html
- test-suite/vocab_template.haml
Hoping to help promote more great community work. 😃
> Add rust implementation

- index.html
Signed-off-by: Tomislav Markovski <tmarkovski@gmail.com>
Updated JSON-LD support for dotNetRDF to 1.1
https://github.com/dotnetrdf/dotnetrdf/pull/316
> Update support version for dotNetRDF to 1.1

- index.html
rdflib-jsonld is now part of rdflib core
> change rdflib-jsonld to just rdflib

- playground/index.html
- playground/playground.js
Fixes: https://github.com/json-ld/json-ld.org/issues/767
- Add compactArrays.
- Add compactToRelative.
> Add api options to playground.

- index.html
- spec/index.php
* Remove note about work now happening in the JSON-LD WG.
* Note change to WG status.
* Reference YAML-LD.
* Use irc.w3.org for IRC instead of Freenode. Add Gitter channel.
> Website updates

- index.html
Getting reports folks can't find your amazing tools, @davidlehn. 😸 This should help a wee bit.
> Add jsonld-cli to Developers section.

- index.html
The previous link was to a specific alpha release.
> Update Sophia link to stable version

- index.html
That's been broken for a few years... >_<
> Update homepage charter link.

- index.html
> Fix version badge of JSON-LD.ex
